### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by jaseilers** [kentaro-m/task-completed-checker-action#48]
This action still uses Node 12 which is out of support since April 2022. Therefore using this action gives a deprecation warning:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: kentaro-m/task-completed-checker-action@v0.1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Comment by kentaro-m** [comment]
Hi, @jaseilers!
Thank you for reporting the outage of support for Node.js 12.
I have already fixed it in #49. Please use v0.1.1 to apply the fix.
