### ISSUE TITLE
Github Enterprise Server (GHES) is not supported

### ISSUE THREAD

**Issue by rajbos** [kentaro-m/task-completed-checker-action#55]
By default the GitHub Octokit client does not check for the `GITHUB_API_URL` environment variable and there for cannot work with GHES. We would still like to use it on GHES, so could you support this?

Here is an example from loading the environment variable: [link](https://github.com/peter-murray/workflow-application-token-action/blob/b1ad34e28f4ef30582df1bd5f45df2044eb7a6b9/lib/github-application.js#L228).

And sending it into the Octokit client [here](https://github.com/peter-murray/workflow-application-token-action/blob/b1ad34e28f4ef30582df1bd5f45df2044eb7a6b9/lib/github-application.js#L56) .

I'd be happy to send in a PR that addresses this.

Tagging @kentaro-m for visibility

**Comment by kentaro-m** [comment]
Hi, @rajbos.
Thank you for reporting the feature request.
I released [v0.1.2](https://github.com/kentaro-m/task-completed-checker-action/releases/tag/v0.1.2) to add support for GHE Server. Can you please try this version to see if it works?

**Comment by melroy89** [comment]
Thanks! We will try.
